project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    collapse: false
    collapse-below: sm
    search: false
    left:
      - text: "<img src='images/logo_name_bw.png' alt='naturenoise' class='navbar-logo' />"
        href: "#start"
        aria-label: Startseite
      - text: konzerte
        href: "#konzerte"
      - text: medien
        href: "#medien"
      - text: kontakt
        href: "#kontakt"

  page-footer:
    center: 
      - text: "Feinste A Capella Musik seit 2009<br>naturenoise | 2026"

format:
  html:
    include-after-body:
      text: |
        <script>
          const navbar = document.querySelector('.navbar');
          window.addEventListener('scroll', () => {
            navbar.classList.toggle('scrolled', window.scrollY > 360);
          });
        </script>
    theme:
      light: flatly
    css: styles.css
    toc: false

editor: visual
